[package]
name = "LTwd"
version = "0.1.0"
edition = "2024"

[dependencies]
egui = "0.27"
eframe = { version = "0.27", default-features = false, features = ["default_fonts", "glow"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.8"
image = "0.25"
rfd = "0.15"
